version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: frontend-container
    restart: always
    networks:
      - app-network

  server:
    build: ./server
    container_name: backend-container
    environment:
      NODE_ENV: production
    links:
      - db
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: mongo:5.0.6
    container_name: db-container
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=WarScape
    restart: always
    volumes:
      - dbdata:/data/db
      - ./server/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
