version: "3.7"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: frontend-container
    restart: always
    volumes:
      - ./client:/usr/src/app

  server:
    build: ./server
    container_name: backend_container
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0.21
    ports:
      - "31003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/:ro
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

volumes:
  dbdata:
