version: '3.7'

services:

  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: frontend-docker
    restart: always
    volumes:
      - ./client:/usr/src/app
    networks:
      - frontend

  db:
    image: mysql:8.0.21
    ports:
      - "31003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - dbdata:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local