version: "3.8"

services:
  client:
    build: ./client
    container_name: frontend-container
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network
      - logging
      - monitoring

  server:
    build: ./server
    container_name: backend-container
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    environment:
      NODE_ENV: production
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - db
      - rabbitmq
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app-network
      - rabbitmq-network
      - internal
      - logging
      - monitoring

  db:
    image: mongo:latest
    container_name: db-container
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    environment:
      - MONGO_INITDB_DATABASE=WarScape
    volumes:
      - dbdata:/data/db
      - ./configs/mongo/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - app-network
      - logging
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring
      - visualizing

  loki:
    image: grafana/loki
    container_name: loki-container
    volumes:
      - ./configs/loki/loki.yml:/etc/config/loki.yml
      - ./configs/loki/wal:/wal
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yml
    ports:
      - 3100:3100
    networks:
      - logging
      - visualizing

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    volumes:
      - grafana_volume:/var/lib/grafana
    ports:
      - 3002:3000
    depends_on:
      - loki
    networks:
      - visualizing

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-container
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - 9000:9000

  kong:
    image: kong:latest
    container_name: kong-container
    volumes:
      - ./configs/kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 8444:8444
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-container
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "exit 0"
    networks:
      - rabbitmq-network

volumes:
  dbdata:
  grafana_volume:
  portainer_data:

networks:
  app-network:
  internal:
  logging:
  visualizing:
  monitoring:
  rabbitmq-network:
